<?php $_order = $this->getOrder() ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('threadflo')->__('Threadflo Order Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('threadflo')->__('Order ID') ?></label></td>
                    <td class="value"><strong><?php echo $_order->getThreadfloOrderId() ? $_order->getThreadfloOrderId() : 'None' ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('threadflo')->__('Status') ?></label></td>
                    <td class="value"><strong><?php echo $_order->getThreadfloOrderStatus() ? $_order->getThreadfloOrderStatus() : 'None' ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
